### PR TITLE
Fix/clarity native bin scripts

### LINKED ISSUE #34: Failed to install clarity-cli native binary during npm install
**OS**: Kubuntu 18.04 x64
**Node version**: 10.16.0
**Npm version**: 6.9.0

**logs below:**

```
Fetching https://github.com/blockstack/clarity-js-sdk/releases/download/clarity-sdk-v0.0.4/clarity-cli-linux-x64.tar.gz
Extracting to temp dir /tmp/PWObdR
Moving /tmp/PWObdR/clarity-cli to /home/nervehammer/clarity-js-sdk/packages/clarity-native-bin/.native-bin/clarity-sdk-v0.0.4/clarity-cli
Failed to install clarity-cli native binary: Error: EXDEV: cross-device link not permitted, rename '/tmp/PWObdR/clarity-cli' -> '/home/nervehammer/clarity-js-sdk/packages/clarity-native-bin/.native-bin/clarity-sdk-v0.0.4/clarity-cli'
child_process.js:650
    throw err;
    ^

Error: Command failed: npx ts-node@^8.2.0 --project /home/nervehammer/clarity-js-sdk/packages/clarity-native-bin/tsconfig.build.json /home/nervehammer/clarity-js-sdk/packages/clarity-native-bin/src/directInstall.ts
    at checkExecSyncError (child_process.js:629:11)
    at Object.execFileSync (child_process.js:647:13)
    at tsNodeInstall (/home/nervehammer/clarity-js-sdk/packages/clarity-native-bin/postInstallScript.js:57:16)
    at Object.<anonymous> (/home/nervehammer/clarity-js-sdk/packages/clarity-native-bin/postInstallScript.js:19:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
lerna info lifecycle @blockstack/clarity-native-bin@0.1.9-alpha.0~postinstall: Failed to exec postinstall script
lerna ERR! lifecycle "postinstall" errored in "@blockstack/clarity-native-bin", exiting 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clarity-monorepo-wrapper@0.0.0 prepare: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the clarity-monorepo-wrapper@0.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nervehammer/.npm/_logs/2019-07-01T10_49_22_531Z-debug.log
```

### PR DESCRIPTION
**Pull request by nervehammer**
fixes #34 #35 

1. added fs-extra's moveSync and removeSync to avoid error `EXDEV: cross-device link not permitted, rename`

2. added shell param to execFileSync in postInstallScript to execute npx in windows env properly.

### CODE REVIEW

File: packages/clarity-native-bin/postInstallScript.js [hunk 1]
```diff
@@ -54,5 +54,5 @@ function tsNodeInstall() {
   const directInstallTsFile = path.join(__dirname, "src", "directInstall.ts");
   const tsNodeExecArgs = [tsNodePkg, "--project", tsConfigBuildFile, directInstallTsFile];
   console.log(`Running: npx ${tsNodeExecArgs.join(" ")}`);
-  childProcess.execFileSync("npx", tsNodeExecArgs, { stdio: ['pipe', process.stdout, process.stderr] });
+  childProcess.execFileSync("npx", tsNodeExecArgs, { stdio: ['pipe', process.stdout, process.stderr], shell: process.platform=="win32" });
```
Comment (lgalabru) [inline packages/clarity-native-bin/postInstallScript.js]: What would be the side effect of the flag `shell: process.platform=="win32"` when running on another distribution (linux, mac, ...)?

Comment (zone117x) [reply packages/clarity-native-bin/postInstallScript.js]: Default is false and I don't think this is overridden with env vars, so should be okay. Tested on macOS
